language: python

php:
  - 2.7

before_script:
  - pip install -r requirements.txt

script:
  - python -m unittest discover -s tests/ -p '*_test.py'

notifications:
  email:
    recipients: project.omosan+vimman-bot@gmail.com
    on_success: always # [always|never|change]
    on_failure: always # [always|never|change]
